### ISSUE TITLE
Visual output of the code

### ISSUE THREAD

**Issue by nikoststs** [paul-pias/Object-Detection-and-Distance-Measurement#10]
Hi everyone, 
I was wondering if there is an optical output after we run the code. 
E.g a video that is the same with the original plus bounding boxes and markers that mark the distance
Or more generally, where can we see the distance information?

**Comment by paul-pias** [comment]
You need to add the following line before cv2.imshow to draw the distance in the frame. However, you can use more **OpenCV** functionalities to draw customized boxes, text, overlay over a frame using cv2.rectangle, cv2.overlay, etc. Anyway, I have updated the repo with few modifications, hope these will solve your issues. 
 frame = cv2.putText(frame, str("{:.2f} Inches".format(distance)), (x,y), cv2.FONT_HERSHEY_DUPLEX, 0.6, (0,0,255), 1, cv2.LINE_AA)
