### ISSUE TITLE
distance_measurement

### ISSUE THREAD

**Issue by nourkarem** [paul-pias/Object-Detection-and-Distance-Measurement#12]
hello, please help to understand equations  for distance estimation
i want to use this part in my project      
1-i donot understand  third equation d=f+R/r      what you mean  is d==do((Distance of object from the lens)?  is R height in image , r height in real?
2-how you get focal length formula?
3-how you get relation distance from w , h as  I use images with size 600*800
4- if there any specs of camera

**Comment by paul-pias** [comment]
Kindly read the discussion in [Issue#3](https://github.com/paul-pias/Object-Detection-and-Distance-Measurement/issues/3#issue-558760754).

**Comment by HassanBinHaroon** [comment]
Check out the following relevant and easiest implementation. 

https://github.com/HassanBinHaroon/object_detection-PLUS-distance_estimation-v1
