### ISSUE TITLE
Use EfficientDet Network

### ISSUE THREAD

**Issue by brunojus** [paul-pias/Object-Detection-and-Distance-Measurement#13]
Hi, 

Is it possible to change the current Yolo model for EfficientDet? I can improve this repo using another model, could you guide me for this update, please?

**Comment by paul-pias** [comment]
Hello @brunojus,
Thank you for your interest. Can you kindly work on a separate branch for **EfficientDet** and make a pull request? I will merge if everything works well and update the repository description accordingly.

**Comment by brunojus** [comment]
Perfect, I will work on it.

**Comment by HassanBinHaroon** [comment]
Check out the following relevant and easiest implementation. 

https://github.com/HassanBinHaroon/object_detection-PLUS-distance_estimation-v1
