### ISSUE TITLE
Platform dependent

### ISSUE THREAD

**Issue by puthusseri** [paul-pias/Object-Detection-and-Distance-Measurement#19]
The library you used "pywin32" can only be used for windows. 

- [ ]  Find an alternative for the respective library for Linux .

**Comment by paul-pias** [comment]
Sorry for the late response. You can see this [issue](https://github.com/paul-pias/Object-Detection-and-Distance-Measurement/issues/2#issuecomment-581038803). Hope it will solve your problem.

**Comment by puthusseri** [comment]
> Sorry for the late response. You can see this [issue](https://github.com/paul-pias/Object-Detection-and-Distance-Measurement/issues/2#issuecomment-581038803). Hope it will solve your problem.

Found it useful. Thank you.
