### ISSUE TITLE
Compatibility issues with Ubuntu while using tts engine for windows

### ISSUE THREAD

**Issue by sabinasalim** [paul-pias/Object-Detection-and-Distance-Measurement#2]
How can I run the project in Ubuntu since the object_detection.py file uses windows "win32com.client" for windows. Is there any alternative tts engine for ubuntu or is it only compatible with windows os.

The error is as follows:
`import win32com.client as wincl 
Traceback (most recent call last):
  File "object_detection.py", line 18, in <module>
 import win32com.client as wincl
ImportError: No module named 'win32com'`

**Comment by paul-pias** [comment]
Thank you for reaching out! 
You can use **espeak** instead of **win32com**.

First, try to install using the following command from your terminal. 

- [ ] `sudo apt-get install espeak python-espeak`

Then import in the object_detection.py script 
- [ ] `from espeak import espeak`

and replace the #244 line with 

- [ ] `espeak.synth("Hello World")`

I hope it will resolve the issue. Kindly let me know if it works or not.

**Comment by sabinasalim** [comment]
Thank you for your response. I have followed the instructions but after installing espeak via pip I encountered another error. In import espeak command returns an error. Adding code for reference.
In pip-list also the espeak package is not found.

`File "object_detection.py",line 18, in <module>
from espeak import speak
ImportError : No module named 'espeak'`

**Comment by paul-pias** [comment]
The previous installation format is for python version <=2.7.
For python3 try the following command 

-  `sudo apt-get install espeak python3-espeak`

Hope it will resolve the issue.

**Comment by sabinasalim** [comment]
Thank you for your response.i have followed the instructions but same error is encountered.
Traceback (most recent call last):
  File "object_detection.py", line 18, in <module>
    from espeak import espeak
ImportError: No module named 'espeak'

**Comment by paul-pias** [comment]
Can you run `pip3 list` and `python3 object_detection.py` from your terminal and share the picture of both the terminals?

**Comment by sabinasalim** [comment]
The above error was recified. But , something new came up. Any idea what this is?


`File "object_detection.py", line 254, in <module>
    object_detection()
  File "object_detection.py", line 147, in object_detection
    model.load_weights(weightsfile)
  File "/home/acer-10/Desktop/object/darknet.py", line 436, in load_weights
    bn_biases = bn_biases.view_as(bn.bias.data)
RuntimeError: shape '[32]' is invalid for input of size 28
`

**Comment by sabinasalim** [comment]
Package         Version  
--------------- ---------
camera          1.3.0    
certifi         2018.8.24
chardet         3.0.4    
Click           7.0      
cycler          0.10.0   
Flask           1.1.1    
gevent          1.4.0    
greenlet        0.4.15   
idna            2.8      
itsdangerous    1.1.0    
Jinja2          2.11.0   
kiwisolver      1.1.0    
MarkupSafe      1.1.1    
matplotlib      3.0.3    
numpy           1.14.2   
opencv-python   4.1.2.30 
pandas          0.25.3   
Pillow          7.0.0    
pip             20.0.2   
pyad            0.6.0    
pyparsing       2.4.6    
python-dateutil 2.8.1    
pytz            2019.3   
requests        2.22.0   
setuptools      40.2.0   
six             1.14.0   
torch           1.4.0    
urllib3         1.25.8   
Werkzeug        0.16.1   
wheel           0.31.1

**Comment by sabinasalim** [comment]
Traceback (most recent call last):
File "object_detection.py", line 18, in 
from espeak import espeak
ImportError: No module named 'espeak'

**Comment by paul-pias** [comment]
Try changing the numpy version to "numpy==1.17.0"

**Comment by shashi-dhuppe** [comment]
HI, I am not able to locate similar thing for Mac. Can you help out? I am currently getting the same error @sabinasalim got when he tired to run in Ubuntu.

**Comment by HassanBinHaroon** [comment]
Check out the following relevant and easiest implementation. No compatibility issues hopefully. 

https://github.com/HassanBinHaroon/object_detection-PLUS-distance_estimation-v1
