### ISSUE TITLE
I take [Errno 2] No such file or directory: 'yolov4.weights'

### ISSUE THREAD

**Issue by Muhammed1244** [paul-pias/Object-Detection-and-Distance-Measurement#33]
In order to solve this error, I downloaded yolov4.weights and put under "YOLOv4" file but I get different error (`error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'`). How can I solve this error? 

I downloaded YOLOv3 and YOLOv4 weights from links you shared ([YOLOv3](https://drive.google.com/drive/folders/1nN49gRqt5HvuMptfc0wRVcuLwiNmMD6u) [YOLOv4](https://drive.google.com/file/d/1cewMfusmPjYWbrnuJRuKhPMwRe_b9PaT/view) ) and I put them under "YOLOv4" file both. 5 file had same name. I changed them with original files. Entire error:  

```
Traceback (most recent call last):
  File "C:\Users\Ahmet\anaconda3\envs\yolou4\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Ahmet\anaconda3\envs\yolou4\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Ahmet\Desktop\Object Detection Projeler\Object-Detection-and-Distance-Measurement\YOLOv4\object_detection.py", line 84, in frame_render
    frame = cv2.resize(frame,(self.width, self.height))
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-dn5w5exm\opencv\modules\imgproc\src\resize.cpp:4051: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
```

**Comment by HassanBinHaroon** [comment]
Check out the following relevant and easiest implementation. 

https://github.com/HassanBinHaroon/object_detection-PLUS-distance_estimation-v1

**Comment by aidansmyth95ifx** [comment]
These weights links are dead for YoloV4
