### ISSUE TITLE
Issues with the weight

### ISSUE THREAD

**Issue by zby5558** [paul-pias/Object-Detection-and-Distance-Measurement#4]
I find that the weights of the project is saved in yolov3.weights. But the weights gotten from the file only has 28 elements. And it makes the whole project fail to run. How to solve this problem

**Comment by HassanBinHaroon** [comment]
Check out the following relevant and easiest implementation. 

https://github.com/HassanBinHaroon/object_detection-PLUS-distance_estimation-v1
