### ISSUE TITLE
Download of videos

### ISSUE THREAD

**Issue by brunojus** [paul-pias/Object-Detection-and-Distance-Measurement#5]
Hi everyone, 

Could you upload the videos in other source please? Because unfortunately I got this error from git lfs.

` response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
`

Thanks in advance

**Comment by paul-pias** [comment]
Can you kindly check it now?

**Comment by brunojus** [comment]
The error still appearing. 

> Error downloading object: 1280.mp4 (e4d84f4): Smudge error: Error downloading 1280.mp4 (e4d84f46df50de3023927121885cc9ee19a818064823c3ed8f7453d2ae11b17e): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by HassanBinHaroon** [comment]
Check out the following relevant and easiest implementation. 

https://github.com/HassanBinHaroon/object_detection-PLUS-distance_estimation-v1
