### ISSUE TITLE
Input frame size for getting the distance result.

### ISSUE THREAD

**Issue by rafiuddinkhan** [paul-pias/Object-Detection-and-Distance-Measurement#6]
I was trying to find the distance of the bounding boxes. What exactly should be the frame size for the formula to work.
you have mentioned 640*480 and getting the bounding boxes and passing the (w,h)
coordinates. I am not getting the results. Can you suggest to replicate the result?

**Comment by paul-pias** [comment]
May I know the result in detail? What is your expected outcome and what you are getting? Are you measuring distance in Inches or in Centimeters?

**Comment by rafiuddinkhan** [comment]
My input frame is 300*300 and using mobilenetv2 for object detection and I am getting the bounding box and passing it to your formula and measuring the distance in inches.

**Comment by paul-pias** [comment]
Kindly check the new update in the repo. Hope it will resolve your issues.

**Comment by and9roid** [comment]
Hello Sir, I am getting as no module found error in line 12 of object_detection.py.Why is this so?
And since i have to use the webcam now and raspberry pi later, what else changes do I need to make in the code for both.
