### ISSUE TITLE
RuntimeError: typeerror: expected PRT <cv::umat> for argument 'src'

### ISSUE THREAD

**Issue by LiQuan19** [paul-pias/Object-Detection-and-Distance-Measurement#9]
Hi,
When I tried to run the code "object_detection.py" for a video. I am able to read the video, resize it. There was a error:
TypeError: Expected cv::UMat for argument 'src',  line:"frame = cv2.resize(frame,(self.width, self.height))"

I am using opencv 4.2.0 on python 3.7. I guess it may be because of version. Which Pytorch Version you are using? Thanks!

**Comment by paul-pias** [comment]
Thank you for reaching out. My python version is 3.6.8 and opencv-python version is  4.2.0.32. There is no such error on my side. Kindly let me know if changing the version resolves your error or not.

**Comment by nikoststs** [comment]
I am having exactly the same issue as  @LiQuan19 . It seems like it doesnt recognize the input video?

**Comment by paul-pias** [comment]
@nikoststs Can you kindly mention your opencv and python version?

**Comment by LiQuan19** [comment]
Hi, I have solved this problem, it should not be a version problem, I changed the "frame = self.cap.read()" to "ret, frame = self.cap.read()".  "self.cap.read()"can return two parameters. @nikoststs .Thanks @paul-pias

**Comment by nikoststs** [comment]
I followed LiQuan19 solution and it did work for me as well.
@paul-pias , i do have another question though. Is there an output video file that shows the distances being measured and the bboxes? ( if it is better to move it to a new question, please do tell me )

**Comment by paul-pias** [comment]
@nikoststs @LiQuan19  Thank you for your cooperation. I will add this in the code segment for future reference.
